// Generated by gencpp from file erau_fusion_msgs/CanBus.msg
// DO NOT EDIT!


#ifndef ERAU_FUSION_MSGS_MESSAGE_CANBUS_H
#define ERAU_FUSION_MSGS_MESSAGE_CANBUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace erau_fusion_msgs
{
template <class ContainerAllocator>
struct CanBus_
{
  typedef CanBus_<ContainerAllocator> Type;

  CanBus_()
    : CarSpeed(0.0)  {
    }
  CanBus_(const ContainerAllocator& _alloc)
    : CarSpeed(0.0)  {
  (void)_alloc;
    }



   typedef float _CarSpeed_type;
  _CarSpeed_type CarSpeed;





  typedef boost::shared_ptr< ::erau_fusion_msgs::CanBus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::erau_fusion_msgs::CanBus_<ContainerAllocator> const> ConstPtr;

}; // struct CanBus_

typedef ::erau_fusion_msgs::CanBus_<std::allocator<void> > CanBus;

typedef boost::shared_ptr< ::erau_fusion_msgs::CanBus > CanBusPtr;
typedef boost::shared_ptr< ::erau_fusion_msgs::CanBus const> CanBusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::erau_fusion_msgs::CanBus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::erau_fusion_msgs::CanBus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace erau_fusion_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'erau_fusion_msgs': ['/home/sabrinayepez/local_talker/src/erau_fusion_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::erau_fusion_msgs::CanBus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::erau_fusion_msgs::CanBus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::erau_fusion_msgs::CanBus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::erau_fusion_msgs::CanBus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::erau_fusion_msgs::CanBus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::erau_fusion_msgs::CanBus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::erau_fusion_msgs::CanBus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc1a7c020ca7ccfab53c9facec5520c4";
  }

  static const char* value(const ::erau_fusion_msgs::CanBus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc1a7c020ca7ccfaULL;
  static const uint64_t static_value2 = 0xb53c9facec5520c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::erau_fusion_msgs::CanBus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "erau_fusion_msgs/CanBus";
  }

  static const char* value(const ::erau_fusion_msgs::CanBus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::erau_fusion_msgs::CanBus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 CarSpeed\n\
";
  }

  static const char* value(const ::erau_fusion_msgs::CanBus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::erau_fusion_msgs::CanBus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.CarSpeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CanBus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::erau_fusion_msgs::CanBus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::erau_fusion_msgs::CanBus_<ContainerAllocator>& v)
  {
    s << indent << "CarSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.CarSpeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ERAU_FUSION_MSGS_MESSAGE_CANBUS_H
