# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from erau_fusion_msgs/tracked_vehicles.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import erau_fusion_msgs.msg
import std_msgs.msg

class tracked_vehicles(genpy.Message):
  _md5sum = "dd7f5ff80dc1711c347504ad53ab7290"
  _type = "erau_fusion_msgs/tracked_vehicles"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
erau_fusion_msgs/tracked_veh_object[32] objects

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: erau_fusion_msgs/tracked_veh_object
erau_fusion_msgs/veh_object object

uint8 id # unique identifier to this object; should remain constant for this object over time
uint16 object_age  # total time this vehicle has been tracked for (in seconds)

# Lane assignment
# 0 - Unknown
# 1 - Left
# 2 - Host/center
# 3 - Right
uint8 lane

# TODO add tracks

================================================================================
MSG: erau_fusion_msgs/veh_object

# Coordinate frames based on center of front fascia at ground level.
# +x is forward, +y is left, +z is up

# Position
float32 x
float32 y
# Position Variance
float32 dx_var
float32 dy_var

# Relative Velocity
float32 dx
float32 dy
# Velocity Variance
float32 vx_var
float32 vy_var

# Classification
# 0 for Unknown
# 1 for car
# 2 for truck
# 3 for pedestrian
uint8 classification

#Car Size
float32 sizeX
float32 sizeY

#Blinker info (from ObstacleData.msg)
# BLINKER_INFO_UNAVAILABLE = 0
# BLINKER_INFO_OFF = 1
# BLINKER_INFO_LEFT = 2
# BLINKER_INFO_RIGHT = 3
# BLINKER_INFO_BOTH = 4
uint8 blinker_info
"""
  __slots__ = ['header','objects']
  _slot_types = ['std_msgs/Header','erau_fusion_msgs/tracked_veh_object[32]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,objects

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(tracked_vehicles, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.objects is None:
        self.objects = [erau_fusion_msgs.msg.tracked_veh_object() for _ in range(32)]
    else:
      self.header = std_msgs.msg.Header()
      self.objects = [erau_fusion_msgs.msg.tracked_veh_object() for _ in range(32)]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      if len(self.objects) != 32:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (32, len(self.objects), 'self.objects')))
      for val1 in self.objects:
        _v1 = val1.object
        _x = _v1
        buff.write(_get_struct_8fB2fB().pack(_x.x, _x.y, _x.dx_var, _x.dy_var, _x.dx, _x.dy, _x.vx_var, _x.vy_var, _x.classification, _x.sizeX, _x.sizeY, _x.blinker_info))
        _x = val1
        buff.write(_get_struct_BHB().pack(_x.id, _x.object_age, _x.lane))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.objects is None:
        self.objects = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      self.objects = []
      for i in range(0, 32):
        val1 = erau_fusion_msgs.msg.tracked_veh_object()
        _v2 = val1.object
        _x = _v2
        start = end
        end += 42
        (_x.x, _x.y, _x.dx_var, _x.dy_var, _x.dx, _x.dy, _x.vx_var, _x.vy_var, _x.classification, _x.sizeX, _x.sizeY, _x.blinker_info,) = _get_struct_8fB2fB().unpack(str[start:end])
        _x = val1
        start = end
        end += 4
        (_x.id, _x.object_age, _x.lane,) = _get_struct_BHB().unpack(str[start:end])
        self.objects.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      if len(self.objects) != 32:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (32, len(self.objects), 'self.objects')))
      for val1 in self.objects:
        _v3 = val1.object
        _x = _v3
        buff.write(_get_struct_8fB2fB().pack(_x.x, _x.y, _x.dx_var, _x.dy_var, _x.dx, _x.dy, _x.vx_var, _x.vy_var, _x.classification, _x.sizeX, _x.sizeY, _x.blinker_info))
        _x = val1
        buff.write(_get_struct_BHB().pack(_x.id, _x.object_age, _x.lane))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.objects is None:
        self.objects = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      self.objects = []
      for i in range(0, 32):
        val1 = erau_fusion_msgs.msg.tracked_veh_object()
        _v4 = val1.object
        _x = _v4
        start = end
        end += 42
        (_x.x, _x.y, _x.dx_var, _x.dy_var, _x.dx, _x.dy, _x.vx_var, _x.vy_var, _x.classification, _x.sizeX, _x.sizeY, _x.blinker_info,) = _get_struct_8fB2fB().unpack(str[start:end])
        _x = val1
        start = end
        end += 4
        (_x.id, _x.object_age, _x.lane,) = _get_struct_BHB().unpack(str[start:end])
        self.objects.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_8fB2fB = None
def _get_struct_8fB2fB():
    global _struct_8fB2fB
    if _struct_8fB2fB is None:
        _struct_8fB2fB = struct.Struct("<8fB2fB")
    return _struct_8fB2fB
_struct_BHB = None
def _get_struct_BHB():
    global _struct_BHB
    if _struct_BHB is None:
        _struct_BHB = struct.Struct("<BHB")
    return _struct_BHB
